# Setup
title:               Raphael Cerqueira
tagline:             ''
description:         ''
url:                 https://rphlfc.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raphael Cerqueira
  url:               https://twitter.com/rphlfc
  email:             email@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-175462661-1
